# Generated by Django 4.1.4 on 2023-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0002_add_question_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("yes_no", "Yes/No"),
                    ("foi", "FOI"),
                    ("select_one", "Select One"),
                    ("tiered", "Tiered Answer"),
                    ("multiple_choice", "Multiple Choice"),
                ],
                default="yes_no",
                max_length=30,
            ),
        ),
    ]
