# Generated by Django 4.1.4 on 2023-01-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0003_add_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="how_marked",
            field=models.CharField(
                choices=[
                    ("foi", "FOI"),
                    ("national_data", "National Data"),
                    ("volunteer", "Volunteer Research"),
                    ("national_volunteer", "National Data and Volunteer Research"),
                ],
                default="volunteer",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("yes_no", "Yes/No"),
                    ("foi", "FOI"),
                    ("national_data", "National Data"),
                    ("select_one", "Select One"),
                    ("tiered", "Tiered Answer"),
                    ("multiple_choice", "Multiple Choice"),
                ],
                default="yes_no",
                max_length=30,
            ),
        ),
    ]
