# Generated by Django 4.1.4 on 2023-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0005_add_extra_question_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="evidence",
            field=models.TextField(
                default="",
                help_text="Please directly copy any evidence you have found to meet the criteria.",
                verbose_name="Evidence of criteria met",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="response",
            name="page_number",
            field=models.IntegerField(
                default=0,
                help_text="Please directly copy the page number from the document where you have found the evidence.",
                verbose_name="Page Number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="response",
            name="private_notes",
            field=models.TextField(
                help_text="Please feel free to add any notes/comments you may have. These will not be made public but will be sent to the Council in the Right of Reply.",
                verbose_name="Additional Notes",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="public_notes",
            field=models.TextField(verbose_name="Public notes (links only)"),
        ),
    ]
