# Generated by Django 4.1.4 on 2023-01-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0006_update_response_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="evidence",
            field=models.TextField(
                blank=True,
                help_text="Please directly copy any evidence you have found to meet the criteria.",
                null=True,
                verbose_name="Evidence of criteria met",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="page_number",
            field=models.IntegerField(
                blank=True,
                help_text="Please directly copy the page number from the document where you have found the evidence.",
                null=True,
                verbose_name="Page Number",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="public_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Public notes (links only)"
            ),
        ),
    ]
