# Generated by Django 4.1.4 on 2023-01-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0007_not_all_response_fields_mandatory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcer.option",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Please feel free to add any notes/comments you may have. These will not be made public but will be sent to the Council in the Right of Reply.",
                verbose_name="Additional Notes",
            ),
        ),
    ]
