# Generated by Django 4.1.4 on 2023-01-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crowdsourcer", "0008_allow_blank_response_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalResponse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Public notes (links only)"
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Please directly copy the page number from the document where you have found the evidence.",
                        null=True,
                        verbose_name="Page Number",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Please directly copy any evidence you have found to meet the criteria.",
                        null=True,
                        verbose_name="Evidence of criteria met",
                    ),
                ),
                (
                    "private_notes",
                    models.TextField(
                        blank=True,
                        help_text="Please feel free to add any notes/comments you may have. These will not be made public but will be sent to the Council in the Right of Reply.",
                        verbose_name="Additional Notes",
                    ),
                ),
                (
                    "revision_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("revision_notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crowdsourcer.publicauthority",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crowdsourcer.option",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crowdsourcer.question",
                    ),
                ),
                (
                    "response_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crowdsourcer.responsetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical response",
                "verbose_name_plural": "historical responses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
