# Generated by Django 4.1.4 on 2023-01-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0010_extra_response_verbose_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="multi_option",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="multi_option",
                to="crowdsourcer.option",
                verbose_name="Multi",
            ),
        ),
    ]
