# Generated by Django 4.1.4 on 2023-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0011_response_multi_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicauthority",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
