# Generated by Django 4.1.4 on 2023-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0012_add_authority_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="multi_option",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_option",
                to="crowdsourcer.option",
                verbose_name="Answer",
            ),
        ),
    ]
