# Generated by Django 4.1.4 on 2023-01-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0013_alter_response_multi_option"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assigned",
            unique_together={("section", "authority")},
        ),
    ]
