# Generated by Django 4.1.4 on 2023-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0014_alter_assigned_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="option",
            name="ordering",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
