# Generated by Django 4.1.4 on 2023-01-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0015_alter_option_options_option_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ["ordering", "score"]},
        ),
    ]
