# Generated by Django 4.1.4 on 2023-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0016_alter_option_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresponse",
            name="page_number",
            field=models.CharField(
                blank=True,
                help_text="Please directly copy the page number from the document where you have found the evidence.",
                max_length=50,
                null=True,
                verbose_name="Page Number",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="page_number",
            field=models.CharField(
                blank=True,
                help_text="Please directly copy the page number from the document where you have found the evidence.",
                max_length=50,
                null=True,
                verbose_name="Page Number",
            ),
        ),
    ]
