# Generated by Django 4.1.6 on 2023-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0017_alter_historicalresponse_page_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicauthority",
            name="do_not_mark",
            field=models.BooleanField(default=False),
        ),
    ]
