# Generated by Django 4.1.6 on 2023-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0020_historicalassigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponse",
            name="agree_with_response",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="agree_with_response",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
