# Generated by Django 4.1.7 on 2023-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0023_historicalresponse_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsetype",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
