# Generated by Django 4.1.7 on 2023-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0025_add_response_type_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigned",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalassigned",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
