# Generated by Django 4.1.7 on 2023-05-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0026_add_assigned_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assigned",
            unique_together={("section", "authority", "response_type")},
        ),
    ]
