# Generated by Django 4.1.7 on 2023-05-04 14:49

from django.db import migrations


def update_response_types(apps, schema_editor):
    Assigned = apps.get_model("crowdsourcer", "Assigned")
    ResponseType = apps.get_model("crowdsourcer", "ResponseType")

    # otherwise we bail when DB is blank
    try:
        first = ResponseType.objects.get(type="First Mark")
        ror = ResponseType.objects.get(type="Right of Reply")
    except ResponseType.DoesNotExist:
        return

    for assigned in Assigned.objects.filter(user__marker__response_type=ror):
        assigned.response_type = ror
        assigned.save()

    for assigned in Assigned.objects.filter(
        response_type__isnull=True, user__is_superuser=False
    ):
        assigned.response_type = first
        assigned.save()


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0027_update_assignment_unique"),
    ]

    operations = [
        migrations.RunPython(update_response_types),
    ]
