# Generated by Django 4.1.9 on 2023-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0028_update_assignment_response_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponse",
            name="foi_answer_in_ror",
            field=models.BooleanField(
                default=False,
                help_text="The council did not respond to the FOI request, but did provide the information as part of their Right of Reply response",
                verbose_name="Responded to in Right of Reply",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="foi_answer_in_ror",
            field=models.BooleanField(
                default=False,
                help_text="The council did not respond to the FOI request, but did provide the information as part of their Right of Reply response",
                verbose_name="Responded to in Right of Reply",
            ),
        ),
    ]
