# Generated by Django 4.2.3 on 2023-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0030_question_weightings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="weighting",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("unweighted", "Unweighted"),
                ],
                default="low",
                max_length=20,
            ),
        ),
    ]
