# Generated by Django 4.2.3 on 2023-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0032_add_authority_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("yes_no", "Yes/No"),
                    ("foi", "FOI"),
                    ("national_data", "National Data"),
                    ("select_one", "Select One"),
                    ("tiered", "Tiered Answer"),
                    ("multiple_choice", "Multiple Choice"),
                    ("negative", "Negatively Marked"),
                ],
                default="yes_no",
                max_length=30,
            ),
        ),
    ]
