# Generated by Django 4.2.3 on 2023-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0033_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponse",
            name="points",
            field=models.FloatField(
                blank=True, help_text="overide marks for this response", null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="points",
            field=models.FloatField(
                blank=True, help_text="overide marks for this response", null=True
            ),
        ),
    ]
