# Generated by Django 4.2.5 on 2024-03-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0035_publicauthority_political_coalition_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marker",
            options={
                "permissions": [
                    ("can_view_all_responses", "Can view all responses"),
                    ("can_view_stats", "Can view stats"),
                ]
            },
        ),
    ]
