# Generated by Django 4.2.5 on 2024-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0036_alter_marker_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
            ],
        ),
    ]
