# Generated by Django 4.2.5 on 2024-04-10 15:16

from django.db import migrations


def add_initial_marking_session(apps, schema_editor):
    MarkingSession = apps.get_model("crowdsourcer", "MarkingSession")

    MarkingSession.objects.create(
        label="Scorecards 2023",
        start_date="2023-03-01",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0037_markingsession"),
    ]

    operations = [
        migrations.RunPython(add_initial_marking_session),
    ]
