# Generated by Django 4.2.5 on 2024-04-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0038_create_initial_marking_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigned",
            name="marking_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcer.markingsession",
            ),
        ),
        migrations.AddField(
            model_name="historicalassigned",
            name="marking_session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crowdsourcer.markingsession",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="marking_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcer.markingsession",
            ),
        ),
    ]
