# Generated by Django 4.2.5 on 2024-04-10 15:43

from django.db import migrations


def link_initial_marking_session(apps, schema_editor):
    MarkingSession = apps.get_model("crowdsourcer", "MarkingSession")
    Assigned = apps.get_model("crowdsourcer", "Assigned")
    Section = apps.get_model("crowdsourcer", "Section")

    initial = MarkingSession.objects.first()

    Assigned.objects.update(marking_session=initial)
    Section.objects.update(marking_session=initial)


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0039_add_marking_session_links"),
    ]

    operations = [
        migrations.RunPython(
            link_initial_marking_session, reverse_code=migrations.RunPython.noop
        ),
    ]
