# Generated by Django 4.2.5 on 2024-04-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0040_link_to_initial_marking_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigned",
            name="marking_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcer.markingsession",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="marking_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcer.markingsession",
            ),
        ),
    ]
