# Generated by Django 4.2.5 on 2024-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0041_make_marking_session_mandatory"),
    ]

    operations = [
        migrations.AddField(
            model_name="markingsession",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
