# Generated by Django 4.2.5 on 2024-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0043_alter_markingsession_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="marking_session",
            field=models.ManyToManyField(null=True, to="crowdsourcer.markingsession"),
        ),
    ]
