# Generated by Django 4.2.11 on 2024-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0045_markingsession_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiongroup",
            name="marking_session",
            field=models.ManyToManyField(to="crowdsourcer.markingsession"),
        ),
    ]
