# Generated by Django 4.2.11 on 2024-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0046_questiongroup_marking_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="markingsession",
            name="entity_name",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
