# Generated by Django 4.2.11 on 2024-05-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0048_alter_marker_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marker",
            options={
                "permissions": [
                    ("can_view_all_responses", "Can view all responses"),
                    ("can_view_progress", "Can view progress"),
                    ("can_view_stats", "Can view stats"),
                    ("can_manage_users", "Can manage users"),
                ]
            },
        ),
    ]
