# Generated by Django 4.2.11 on 2024-06-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0049_alter_marker_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="previous_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crowdsourcer.question",
            ),
        ),
    ]
