# Generated by Django 4.2.11 on 2024-06-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0050_add_previous_q_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_name", models.CharField(max_length=200)),
                ("data_value", models.TextField()),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowdsourcer.publicauthority",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["authority", "data_name"],
                        name="crowdsource_authori_49003f_idx",
                    )
                ],
            },
        ),
    ]
