# Generated by Django 4.2.11 on 2024-06-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0051_authoritydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicauthority",
            name="marking_session",
            field=models.ManyToManyField(to="crowdsourcer.markingsession"),
        ),
    ]
