# Generated by Django 4.2.30 on 2026-06-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0060_question_read_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="how_marked",
            field=models.CharField(
                choices=[
                    ("foi", "FOI"),
                    ("national_data", "National Data"),
                    (
                        "national_data_ror_visible",
                        "National Data visible in Right of Reply",
                    ),
                    ("volunteer", "Volunteer Research"),
                    ("national_volunteer", "National Data and Volunteer Research"),
                ],
                default="volunteer",
                max_length=30,
            ),
        ),
    ]
