# Generated by Django 4.2.30 on 2026-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0061_alter_question_how_marked"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="first_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
